import demo from "../assets/demo.jpg";

export const PRODUCTS = [
    {
        id: 1,
        productName: "IPhone",
        price: 912399.765,
        productImage: demo,
        timeLimit: "56",
        delDate: "12/34/5",
        owner: "Bill Gates",
        rating: 5,
        tags: ["all", "", "island", ""],
    },
    {
        id: 2,
        productName: "MacBook Air",
        price: 999.0,
        productImage: demo,
        timeLimit: "32",
        delDate: "12/34/5",
        owner: "Mukesh Ambani",
        rating: 5,
        tags: ["all", "", "rare", ""],
    },
    {
        id: 3,
        productName: "iMac",
        price: 999.0,
        productImage: demo,
        timeLimit: "12",
        delDate: "10/02/5",
        owner: "Mark Zucherberg",
        rating: 5,
        tags: ["all", "", "island", ""],
    },
    {
        id: 4,
        productName: "Samsung Galaxy Note",
        price: 999.0,
        productImage: demo,
        timeLimit: "12",
        delDate: "10/02/5",
        owner: "Amancio Ortago",
        rating: 5,
        tags: ["all", "", "space", ""],
    },
    {
        id: 5,
        productName: "LG QLED 85 inch",
        price: 999.0,
        productImage: demo,
        timeLimit: "12",
        delDate: "10/02/5",
        owner: "Elon Musk",
        rating: 5,
        tags: ["all", "", "space", ""],
    },
    {
        id: 6,
        productName: "Nvidia GPU",
        price: 999.0,
        productImage: demo,
        timeLimit: "32",
        delDate: "12/34/5",
        owner: "Mukesh Ambani",
        rating: 5,
        tags: ["all", "", "island", ""],
    },
    {
        id: 7,
        productName: "Canon D3500",
        price: 999.0,
        productImage: demo,
        timeLimit: "56",
        delDate: "12/34/5",
        owner: "Bill Gates",
        rating: 5,
        tags: ["all", "", "", "rare"],
    },
    {
        id: 8,
        productName: "iPhone 14 Pro Max",
        price: 999.0,
        productImage: demo,
        timeLimit: "12",
        delDate: "10/02/5",
        owner: "Elon Musk",
        rating: 5,
        tags: ["all", "", "", "rare"],
    },
];